version: "3"
 
services:
  jenkins:
    user: root
    image: "jenkins/jenkins:jdk11"
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
  sonarqube:
    image: "sonarqube:developer"
    ports:
      - "9000:9000"
    networks:
     - mynet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - mynet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  remnux:
    image: remnux/remnux-distro
    volumes:
     - .:/home/remnux/files
    networks:
      - mynet
  owaspzap:
    user: zap
    image: owasp/zap2docker-stable
    ports:
      - "8081:8080"
      - "8090:8090"
    command: zap-webswing.sh
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:

